### ISSUE TITLE
Limit per feed option has no effect

### ISSUE THREAD

**Issue by kavadas** [joomlaworks/simple-rss-feed-reader#1]
The option " Maximum items to fetch per feed" has no effect. More information at http://www.joomlaworks.net/forum/simple-rss-feed-reader/40968-why-does-it-fetch-so-much-items

**Comment by april2915** [comment]
Hi,

Any update on this issue? Or any estimated date for the patch? Thanks.

**Comment by fevangelou** [comment]
Fixed in v3.4: https://github.com/joomlaworks/simple-rss-feed-reader/archive/master.zip
