### ISSUE TITLE
Code to set the Time Zone of the module

### ISSUE THREAD

**Issue by ganar** [joomlaworks/simple-rss-feed-reader#5]
Even though there are multiple request to solve this issue, none of them worked for us, so we hacked `modules/mod_jw_srfr/helper.php` like this after line 49

`date_default_timezone_set('America/Caracas');` 

Setting this value before this line has no effect.

Instead of setting the time- zone like this, it can be read from `/configuration.php`

cc @fevangelou

**Comment by fevangelou** [comment]
The only problem is that Joomla simply passes an hour offset, not the timezone.

Have you checked if PHP sets the correct timezone in your server's php.ini configuration?

**Comment by fevangelou** [comment]
In any case, I guess it wouldn't hurt to have a <select> box with all timezones inside the module's parameters. Marking as an enhancement to fix.

**Comment by ganar** [comment]
> Have you checked if PHP sets the correct timezone in your server's php.ini configuration?

Of course: we checked all the usual suspects before doing this change, including the timezone of the installation and the timezone of the server. There is even a bug in Joomla that makes this unworkable if you add the code before that line.

We had this problem for months, in the end we hire someone to correct it

**Comment by ganar** [comment]
I no longer use Joomla. I'm closing this one.
